# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ex_grpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rex_grpc.proto\"&\n\x18\x41nExamplegRPCCallRequest\x12\n\n\x02id\x18\x01 \x01(\t\"5\n\x19\x41nExamplegRPCCallResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t2^\n\x10\x41nExampleService\x12J\n\x11\x41nExamplegRPCCall\x12\x19.AnExamplegRPCCallRequest\x1a\x1a.AnExamplegRPCCallResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ex_grpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ANEXAMPLEGRPCCALLREQUEST._serialized_start=17
  _ANEXAMPLEGRPCCALLREQUEST._serialized_end=55
  _ANEXAMPLEGRPCCALLRESPONSE._serialized_start=57
  _ANEXAMPLEGRPCCALLRESPONSE._serialized_end=110
  _ANEXAMPLESERVICE._serialized_start=112
  _ANEXAMPLESERVICE._serialized_end=206
# @@protoc_insertion_point(module_scope)
