# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ex_grpc_pb2 as ex__grpc__pb2


class AnExampleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnExamplegRPCCall = channel.unary_unary(
                '/AnExampleService/AnExamplegRPCCall',
                request_serializer=ex__grpc__pb2.AnExamplegRPCCallRequest.SerializeToString,
                response_deserializer=ex__grpc__pb2.AnExamplegRPCCallResponse.FromString,
                )


class AnExampleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnExamplegRPCCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnExampleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnExamplegRPCCall': grpc.unary_unary_rpc_method_handler(
                    servicer.AnExamplegRPCCall,
                    request_deserializer=ex__grpc__pb2.AnExamplegRPCCallRequest.FromString,
                    response_serializer=ex__grpc__pb2.AnExamplegRPCCallResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AnExampleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AnExampleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnExamplegRPCCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AnExampleService/AnExamplegRPCCall',
            ex__grpc__pb2.AnExamplegRPCCallRequest.SerializeToString,
            ex__grpc__pb2.AnExamplegRPCCallResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
